apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dawn-patrol.fullname" . }}
  labels:
    {{- include "dawn-patrol.labels" . | nindent 4 }}
stringData:
  {{- range $k,$v := .Values.secretEnv }}
  {{ $k }}: {{ tpl (toString $v) $ | quote }}
  {{- end }}
